[package]
name = "linear_regression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ml_models"
path = "src/lib.rs"

[dependencies]
